{
 "title": "Example dash",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Python-app status",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"python-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Python-app http req",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_count{job=\"python-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus Open FDS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "process_open_fds{job=\"prometheus\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}